---
- name: Incluye el archivo con las variables
  ansible.builtin.include_vars:
    file: vars_main.yml

- name: Instalación ZFS
  ansible.builtin.apt:
    name: ['zfsutils-linux']
    update_cache: true
    cache_valid_time: 3600

- name: Creando "{{ zfs_pool_name }}" para sedes
  ansible.builtin.command: zpool create -O compression=gzip -f "{{ zfs_pool_name }}" raidz "{{ zfs_pool_dev1 }}" "{{ zfs_pool_dev2 }}"  -o ashift=12
  changed_when: false

- name: Creando filesystems en "{{ zfs_pool_name }}"
  community.general.zfs:
    name: "{{ zfs_pool_name }}/{{ item }}"
    state: present
    extra_zfs_properties:
      sharesmb: 'on'
  with_items:
    - sueldos
    - administracion
    - sistemas

- name: Cambiando permisos de acceso a compartida
  ansible.builtin.file:
    path: "/{{ zfs_pool_name }}/{{ item.compartida }}"
    owner: root
    group: "{{ item.grupo }}"
    mode: 0775
  with_items:
    - { compartida: sueldos, grupo: sueldos }
    - { compartida: administracion, grupo: administracion }
    - { compartida: sistemas, grupo: sistemas }
  notify: servicio_samba
