---
- name: Incluye el archivo con las variables
  include_vars:
    file: vars_main.yml

- name: Configuración de archivo smb.conf
  blockinfile:
    path: "{{ ruta_smb }}/smb.conf"
    block: | 
      [global]
      server string = FileServer
      workgroup = WORKGROUP
      security = user
      map to guest = Bad User
      name resolve order = bcast host
      include = /etc/samba/{{ samba_conf }}    
    backup: yes

- name: Creacion de carpetas para compartir
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: vagrant
    group: "{{ grupos }}"
    mode: 0755
  with_items: 
    - "{{ carpetas_compartidas }}_publicos"  
    - "{{ carpetas_compartidas }}_privados"

- name: Copiando archivos de configuracion
  template:
    src: "files/{{ samba_conf }}.j2"
    dest:  "{{ ruta_smb }}/{{ samba_conf }}"
  notify: servicio_samba
