---
- name: Incluye el archivo con las variables
  ansible.builtin.include_vars:
    file: vars_main.yml

- name: Instalación Samba
  ansible.builtin.apt:
    name: ['samba']
    update_cache: true
    cache_valid_time: 3600

- name: Creando los grupos
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  with_items: "{{ grupos }}"

- name: "Creando los usuarios para {{ grupos[0] }}"
  ansible.builtin.user:
    name: "{{ item.nombre }}"
    create_home: false
    password: '!'
    shell: "/bin/false"
    groups: "{{ item.grupo }}"
    update_password: on_create
  with_items: "{{ usuarios }}"

- name: Configurando el password para acceso a samba de los usuarios
  ansible.builtin.shell: "printf '{{ item.password }}\n{{ item.password }}\n' | smbpasswd -s -a {{ item.nombre }}"
  with_items: "{{ usuarios }}"